Importing the Libraries and reading the datasets

In [32]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('Travel.csv')
print(f"Loaded Dataset: {df.shape[0]} rows , {df.shape[1]} columns")

Loaded Dataset: 4888 rows , 20 columns

In [33]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [35]:
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [36]:
#checking for Duplicates
df.duplicated().sum()

np.int64(0)

In [38]:
#checking for Missing values
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [39]:
#Filling the missing values
df['Age'] = df.groupby('Designation')['Age'].transform(lambda x:x.fillna(x.median()))
df['TypeofContact'] = df['TypeofContact'].fillna(df['TypeofContact'].mode()[0])
df['DurationOfPitch'] = df.groupby('ProductPitched')['DurationOfPitch'].transform(lambda x:x.fillna(x.median()))
df['NumberOfFollowups'] = df.groupby('DurationOfPitch')['NumberOfFollowups'].transform(lambda x:x.fillna(x.median()))
df['PreferredPropertyStar'] = df.groupby('ProductPitched')['PreferredPropertyStar'].transform(lambda x:x.fillna(x.mean()))
df['NumberOfTrips'] = df['NumberOfTrips'].fillna(df['NumberOfTrips'].median())
df['NumberOfChildrenVisiting']=df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mean())
df['MonthlyIncome'] = df.groupby('Designation')['MonthlyIncome'].transform(lambda x: x.fillna(x.median()))

In [40]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [41]:
#Fixing the columns
df.columns = df.columns.str.lower()
df = df.rename(columns={
    'customerid': 'customer_id',
    'prodtaken': 'prod_taken',
    'typeofcontact':'type_of_contact',
    'citytier' : 'city_tier',
    'durationofpitch':'duration_of_pitch',
    'numberofpersonvisiting': 'number_of_person_visiting',
    'numberoffollowups': 'number_of_followups',
    'productpitched': 'product_pitched',
    'preferredpropertystar': 'preferred_property_star',
    'maritalstatus': 'marital_status',
    'numberoftrips': 'number_of_trips',
    'pitchsatisfactionscore': 'pitch_satisfaction_score',
    'owncar': 'own_car',
    'numberofchildrenvisiting': 'number_of_children_visiting',
    'monthlyincome': 'monthly_income'
})
df.columns

Index(['customer_id', 'prod_taken', 'age', 'type_of_contact', 'city_tier',
       'duration_of_pitch', 'occupation', 'gender',
       'number_of_person_visiting', 'number_of_followups', 'product_pitched',
       'preferred_property_star', 'marital_status', 'number_of_trips',
       'passport', 'pitch_satisfaction_score', 'own_car',
       'number_of_children_visiting', 'designation', 'monthly_income'],
      dtype='object')

In [42]:
#Fixing the datatypes
df['number_of_children_visiting'] = df['number_of_children_visiting'].astype(int)
df['number_of_followups'] = df['number_of_followups'].astype('int')
df['number_of_trips']= df['number_of_trips'].astype('int')
df['age'] = df['age'].astype('int')
df['duration_of_pitch'] = df['duration_of_pitch'].astype('int')
df['monthly_income'] = df['monthly_income'].astype('int')

In [43]:
df.dtypes

customer_id                      int64
prod_taken                       int64
age                              int64
type_of_contact                 object
city_tier                        int64
duration_of_pitch                int64
occupation                      object
gender                          object
number_of_person_visiting        int64
number_of_followups              int64
product_pitched                 object
preferred_property_star        float64
marital_status                  object
number_of_trips                  int64
passport                         int64
pitch_satisfaction_score         int64
own_car                          int64
number_of_children_visiting      int64
designation                     object
monthly_income                   int64
dtype: object

In [44]:
df['gender'].unique()

array(['Female', 'Male', 'Fe Male'], dtype=object)

In [45]:
df['gender'] = df['gender'].replace('Fe Male','Female')
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [46]:
df.columns

Index(['customer_id', 'prod_taken', 'age', 'type_of_contact', 'city_tier',
       'duration_of_pitch', 'occupation', 'gender',
       'number_of_person_visiting', 'number_of_followups', 'product_pitched',
       'preferred_property_star', 'marital_status', 'number_of_trips',
       'passport', 'pitch_satisfaction_score', 'own_car',
       'number_of_children_visiting', 'designation', 'monthly_income'],
      dtype='object')

In [47]:
df['age'].unique()

array([41, 49, 37, 33, 32, 59, 30, 38, 36, 35, 31, 34, 28, 29, 22, 53, 21,
       42, 44, 46, 39, 24, 43, 50, 27, 26, 48, 55, 45, 56, 23, 51, 40, 54,
       58, 20, 25, 19, 57, 52, 47, 18, 60, 61])

In [48]:
labels = ['young','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q = 4,labels = labels)

     age_group  age
0  Middle-aged   41
1       Senior   49
2  Middle-aged   37
3        Adult   33
4        Adult   32
5        Adult   32
6       Senior   59
7        young   30
8  Middle-aged   38
9        Adult   36

In [50]:
df.insert(3, 'age_group', df.pop('age_group'))

In [51]:
df.columns

Index(['customer_id', 'prod_taken', 'age', 'age_group', 'type_of_contact',
       'city_tier', 'duration_of_pitch', 'occupation', 'gender',
       'number_of_person_visiting', 'number_of_followups', 'product_pitched',
       'preferred_property_star', 'marital_status', 'number_of_trips',
       'passport', 'pitch_satisfaction_score', 'own_car',
       'number_of_children_visiting', 'designation', 'monthly_income'],
      dtype='object')